UPDATE M_OPSMR_HR
SET    SUBSIDIARY = 'LGEAK'
WHERE  SUBSIDIARY = 'LGEAK Factory'
;

UPDATE M_OPSMR_HR
SET    SUBSIDIARY = 'LGEEG'
WHERE  SUBSIDIARY = 'LGEEG Factory'
;

UPDATE M_OPSMR_HR
SET    SUBSIDIARY = 'LGEIL(Noida)'
WHERE  SUBSIDIARY = 'LGEIL Noida Factory'
;

UPDATE M_OPSMR_HR
SET    SUBSIDIARY = 'LGEIL(Pune)'
WHERE  SUBSIDIARY = 'LGEIL Pune Factory'
;

UPDATE M_OPSMR_HR
SET    SUBSIDIARY = 'LGEIN(Cibit)'
WHERE  SUBSIDIARY = 'LGEIN Cibitung Factory'
;

UPDATE M_OPSMR_HR
SET    SUBSIDIARY = 'LGEIN(Ref)'
WHERE  SUBSIDIARY = 'LGEIN Tanggerang Factory'
;

UPDATE M_OPSMR_HR
SET    SUBSIDIARY = 'LGERA'
WHERE  SUBSIDIARY = 'LGERA Ruza Factory'
;

UPDATE M_OPSMR_HR
SET    SUBSIDIARY = 'LGERA'
WHERE  SUBSIDIARY = 'LGERA Ruza Factory'
;

UPDATE M_OPSMR_HR
SET    SUBSIDIARY = 'LGESA'
WHERE  SUBSIDIARY = 'LGESA Factory'
;

UPDATE M_OPSMR_HR
SET    SUBSIDIARY = 'LGESP'
WHERE  SUBSIDIARY = 'LGESP Taubate Factory'
;

UPDATE M_OPSMR_HR
SET    SUBSIDIARY = 'LGESP(Mao)'
WHERE  SUBSIDIARY = 'LGESP Manaus Factory'
;

UPDATE M_OPSMR_HR
SET    SUBSIDIARY = 'LGETH'
WHERE  SUBSIDIARY = 'LGETH Rayong Factory'
;

/*
매핑불가
LGENB
LGENT
LGENV
*/